-- Vendored from nvim-lspconfig's lsp/intelephense.lua, extended with global
-- php-stubs discovery so intelephense picks up globally-installed stub
-- packages (e.g. `composer global require php-stubs/woocommerce-stubs`)
-- without any project-local configuration.

--- Resolve global php-stubs install dirs, if any. Composer's global vendor
--- may live under the legacy `~/.composer` or XDG-style `~/.config/composer`
--- depending on its config, so both are probed and only existing ones kept.
---@return string[]
local function stub_include_paths()
  local ok, home = pcall(vim.uv.os_homedir)
  if not ok or not home then
    return {}
  end

  local candidates = {
    vim.fs.joinpath(home, ".composer", "vendor", "php-stubs"),
    vim.fs.joinpath(home, ".config", "composer", "vendor", "php-stubs"),
  }

  local paths = {}
  for _, path in ipairs(candidates) do
    local stat_ok, stat = pcall(vim.uv.fs_stat, path)
    if stat_ok and stat and stat.type == "directory" then
      paths[#paths + 1] = path
    end
  end
  return paths
end

-- Explicit stub catalogue (rather than intelephense's bundled defaults) so
-- stub coverage stays stable across intelephense versions.
local stubs = {
  "aerospike",
  "amqp",
  "apache",
  "apcu",
  "ast",
  "bcmath",
  "blackfire",
  "bz2",
  "calendar",
  "cassandra",
  "com_dotnet",
  "Core",
  "couchbase",
  "couchbase_v2",
  "crypto",
  "ctype",
  "cubrid",
  "curl",
  "date",
  "dba",
  "decimal",
  "dio",
  "dom",
  "ds",
  "eio",
  "elastic_apm",
  "enchant",
  "Ev",
  "event",
  "exif",
  "expect",
  "fann",
  "FFI",
  "ffmpeg",
  "fileinfo",
  "filter",
  "fpm",
  "frankenphp",
  "ftp",
  "gd",
  "gearman",
  "geoip",
  "geos",
  "gettext",
  "gmagick",
  "gmp",
  "gnupg",
  "grpc",
  "hash",
  "http",
  "ibm_db2",
  "iconv",
  "igbinary",
  "imagick",
  "imap",
  "inotify",
  "interbase",
  "intl",
  "json",
  "judy",
  "ldap",
  "leveldb",
  "libevent",
  "libsodium",
  "libvirt-php",
  "libxml",
  "lua",
  "LuaSandbox",
  "lzf",
  "mailparse",
  "mapscript",
  "mbstring",
  "memcache",
  "memcached",
  "meminfo",
  "meta",
  "ming",
  "mongo",
  "mongodb",
  "mosquitto-php",
  "mqseries",
  "msgpack",
  "mysql",
  "mysql_xdevapi",
  "mysqli",
  "ncurses",
  "newrelic",
  "oauth",
  "oci8",
  "odbc",
  "openssl",
  "opentelemetry",
  "pam",
  "parallel",
  "Parle",
  "pcntl",
  "pcov",
  "pcre",
  "pdflib",
  "PDO",
  "pdo_ibm",
  "pdo_mysql",
  "pdo_pgsql",
  "pdo_sqlite",
  "pgsql",
  "Phar",
  "phpdbg",
  "posix",
  "pq",
  "pspell",
  "pthreads",
  "radius",
  "random",
  "rar",
  "rdkafka",
  "readline",
  "redis",
  "Reflection",
  "regex",
  "relay",
  "rpminfo",
  "rrd",
  "SaxonC",
  "session",
  "shmop",
  "simple_kafka_client",
  "SimpleXML",
  "snappy",
  "snmp",
  "soap",
  "sockets",
  "sodium",
  "solr",
  "SPL",
  "SplType",
  "SQLite",
  "sqlite3",
  "sqlsrv",
  "ssh2",
  "standard",
  "stats",
  "stomp",
  "suhosin",
  "superglobals",
  "svm",
  "svn",
  "swoole",
  "sybase",
  "sync",
  "sysvmsg",
  "sysvsem",
  "sysvshm",
  "tidy",
  "tokenizer",
  "uopz",
  "uploadprogress",
  "uuid",
  "uv",
  "v8js",
  "win32service",
  "winbinder",
  "wincache",
  "xdebug",
  "xdiff",
  "xhprof",
  "xlswriter",
  "xml",
  "xmlreader",
  "xmlrpc",
  "xmlwriter",
  "xsl",
  "xxtea",
  "yaf",
  "yaml",
  "yar",
  "zend",
  "Zend OPcache",
  "ZendCache",
  "ZendDebugger",
  "ZendUtils",
  "zip",
  "zlib",
  "zmq",
  "zookeeper",
  "zstd",
  -- WordPress related
  "acf-pro",
  "acf-stubs",
  "genesis",
  "polylang",
  "woocommerce",
  "wordpress",
  "wordpress-global",
  "wordpress-globals",
  "wp-cli",
}

---@type vim.lsp.Config
return {
  cmd = { "intelephense", "--stdio" },
  filetypes = { "php" },
  -- WP-only; keep the composer/git root so nested plugin repos index themselves, not the whole install.
  root_dir = function(bufnr, on_dir)
    local wp = require("mars.helpers.php_project").wp_root(bufnr)
    if wp then
      on_dir(vim.fs.root(bufnr, { "composer.json", ".git" }) or wp)
    end
  end,
  settings = {
    intelephense = {
      telemetry = {
        enabled = false,
      },
      environment = {
        includePaths = stub_include_paths(),
      },
      stubs = stubs,
    },
  },
}
